import pytest
from neofs_testlib.env.env import NeoFSEnv


def test_neofs_cli_excessive_flags(neofs_env: NeoFSEnv):
    for cmd in (
        "accounting balance address 10123",
        "acl extended create cid",
        "container create name c1",
        "container delete address 10123",
        "container get address 10123",
        "container get-eacl address 10123",
        "container list address 10123",
        "container list-objects address 10123",
        "container nodes r 10123",
        "container set-eacl r 10123",
        "control drop-objects address 10123",
        "control healthcheck address 10123",
        "control notary list address 10123",
        "control notary sign address 10123",
        "control object list address 10123",
        "control object revive address 10123",
        "control object status address 10123",
        "control set-status address 10123",
        "control shards dump address 10123",
        "control shards evacuate address 10123",
        "control shards flush-cache address 10123",
        "control shards list address 10123",
        "control shards restore address 10123",
        "control shards set-mode address 10123",
        "netmap epoch address 10123",
        "netmap netinfo address 10123",
        "netmap nodeinfo address 10123",
        "netmap snapshot address 10123",
        "bearer create expire-at 101123",
        "object delete bearer c1",
        "object get bearer c1",
        "object hash bearer c1",
        "object head bearer c1",
        "object lock bearer c1",
        "object nodes bearer c1",
        "object put bearer c1",
        "object range bearer c1",
        "object search bearer c1",
        "object searchv2 bearer c1",
        "session create address 10123",
        "storagegroup delete address 10123",
        "storagegroup get address 10123",
        "storagegroup list address 10123",
        "storagegroup put address 10123",
        "util convert eacl address 10123",
        "util sign bearer-token address 10123",
        "util sign session-token address 10123",
    ):
        with pytest.raises(Exception, match=".*unknown command.*"):
            neofs_env.shell.exec(f"{neofs_env.neofs_cli_path} {cmd}")
