name: Run tests

on:
  workflow_dispatch:

jobs:
  run_tests:
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - name: Checkout neofs-testcases repository
      uses: actions/checkout@v3
      with:
        repository: nspcc-dev/neofs-testcases

    - name: Checkout neofs-dev-env repository
      uses: actions/checkout@v3
      with:
        repository: nspcc-dev/neofs-dev-env
        path: neofs-dev-env

    - name: Checkout neofs-node repository
      uses: actions/checkout@v3
      with:
        repository: nspcc-dev/neofs-node
        path: neofs-node

    - name: Checkout neofs-s3-gw repository
      uses: actions/checkout@v3
      with:
        repository: nspcc-dev/neofs-s3-gw
        path: neofs-s3-gw

    - name: Checkout neo-go repository
      uses: actions/checkout@v3
      with:
        repository: nspcc-dev/neo-go
        path: neo-go
        ref: v0.92.0

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Set up Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate &&
        sudo apt-get update
        sudo apt-get install -y make python3.10-dev libssl-dev default-jre
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install neofs-cli
      run: |
        cd neofs-node
        make
        sudo cp bin/neofs-cli /usr/local/bin/neofs-cli

    - name: Install neofs-authmate
      run: |
        cd neofs-s3-gw
        make
        sudo cp bin/neofs-s3-authmate /usr/local/bin/neofs-s3-authmate

    - name: Install neo-go
      run: |
        cd neo-go
        make
        sudo cp bin/neo-go /usr/local/bin/neo-go

    - name: Copy releases_versions_env file to .env in neofs-dev-env
      run: |
        cp releases_versions_env ../neofs-dev-env/.env

    - name: Prepare test environment
      run: |
        cd neofs-dev-env
        make prepare-test-env

    - name: Run tests
      run: source venv/bin/activate && pytest --alluredir allure-report pytest_tests/testsuites/

    - name: Cleanup test environment
      run: |
        cd neofs-dev-env
        make down
        make clean

    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-report
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
