name: Run tests

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: self-hosted
#    runs-on: ubuntu-latest
    steps:
    - name: Check node
      run: |
        ip a
        docker network ls
        openssl version -d
        cat /usr/lib/ssl/openssl.cnf

    # Checkout NEOFS parts for the test environment
    # neofs-testcases
    - name: Checkout neofs-testcases repository
      uses: actions/checkout@v3
      with:
        repository: vvarg229/neofs-testcases
        ref: github-actions
        path: neofs-testcases

    # neofs-dev-env
    - name: Checkout neofs-dev-env repository
      uses: actions/checkout@v3
      with:
        repository: nspcc-dev/neofs-dev-env
        ref: master
        path: neofs-dev-env

    # neofs-node
    - name: Checkout neofs-node repository
      uses: actions/checkout@v3
      with:
        repository: nspcc-dev/neofs-node
        ref: v0.35.0
        path: neofs-node

    # neofs-s3-gw
    - name: Checkout neofs-s3-gw repository
      uses: actions/checkout@v3
      with:
        repository: nspcc-dev/neofs-s3-gw
        ref: v0.26.1
        path: neofs-s3-gw

    # neo-go
    - name: Checkout neo-go repository
      uses: actions/checkout@v3
      with:
        repository: nspcc-dev/neo-go
        ref: v0.101.0
        path: neo-go

    # Prerequisites
    # Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'

    # Check Python
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

#    # Create the basenet_internet docker external network manually
#    - name: Create basenet_internet
#      run: docker network create basenet_internet
#
#    # List docker networks
#    - name: Check basenet_internet
#      run: docker network ls

    - name: Create Docker network
      run: docker network create -d macvlan --subnet=192.168.100.0/24 --gateway=192.168.100.1 -o parent=eth0 my_macvlan_network


#    - name: Install net-tools
#      run: sudo apt-get update && sudo apt-get install -y net-tools
#
#    - name: Create network interface
#      run: |
#        sudo ip link add eth100 type dummy
#        sudo ip addr add 192.168.100.5/24 dev eth100
#        sudo ip link set eth100 up

    - name: Verify network interface
      run: |
        ip a

      # Dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make python3.10-dev libssl-dev default-jre 
        sudo apt-get install -y make openssl expect jq coreutils awscli 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: neofs-testcases

    # Install NEOFS parts on runner
    # Install neofs-cli
    - name: Install neofs-cli
      run: |
        make
        sudo cp bin/neofs-cli /usr/local/bin/neofs-cli
      working-directory: neofs-node

    # Install neofs-s3-authmate
    - name: Install neofs-s3-authmate
      run: |
        make
        sudo cp bin/neofs-s3-authmate /usr/local/bin/neofs-s3-authmate
      working-directory: neofs-s3-gw

    # Install neo-go
    - name: Install neo-go
      run: |
        make
        sudo cp bin/neo-go /usr/local/bin/neo-go
      working-directory: neo-go

    # Transfer the env file for the NEOFS test cluster deployment to docker
    - name: Copy releases_versions_env file to .env in neofs-dev-env
      run: |
        ls -la ${GITHUB_WORKSPACE}
        ls -la ${GITHUB_WORKSPACE}/neofs-dev-env
        cp releases_versions_env ${GITHUB_WORKSPACE}/neofs-dev-env/.env
      working-directory: neofs-testcases

    # Check before make the NEOFS test cluster
    - name: Check env files
      run: |
        pwd
        ls -la neo-go
        ls -la neofs-dev-env
        ls -la neofs-node
        ls -la neofs-s3-gw
        ls -la neofs-testcases

    # Get vendor
    - name: Get vendor
      run: |
        pwd
        make get
      working-directory: neofs-dev-env

    # Generate hosts
    - name: Generate hosts
      run: |
        make hosts | sudo tee -a /etc/hosts
      working-directory: neofs-dev-env

    # Check hosts
    - name: Check hosts
      run: |
        pwd
        cat /etc/hosts
      working-directory: neofs-dev-env

    # Prepare test environment
    - name: Prepare test environment
      run: |
        pwd
        ls -la
        ls ..
        make prepare-test-env
      working-directory: neofs-dev-env

    # Make venv
    - name: Prepare test environment
      run: |
        make venv.local-pytest
      working-directory: neofs-testcases

    # Run tests
    - name: Run tests
      run: source venv.local-pytest/bin/activate && pytest --alluredir allure-report pytest_tests/testsuites/
      working-directory: neofs-testcases

    # Cleanup test environment
    - name: Cleanup test environment
      run: | 
        make down
        make clean
      working-directory: neofs-dev-env

    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-report
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
